version: '3.8'
services:
  app:
    build:
      context: ./rest-api
    ports:
      - "3000:3000"
    container_name: 08-nfc-mananger-rest-api
    env_file:
      - ./rest-api/.env
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./rest-api/database:/docker-entrypoint-initdb.d
    container_name: 08-nfc-mananger-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - db
